spring:
   application:
    name: zuulserver
server:
  port: 8093
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
zuul:
  routes:
    user:
       path: /user/**
       service-id: userservice
     
    note:
       service-id: noteservice
       path: /note/**
      